import { SpeedInsights } from "@vercel/speed-insights/next"

import './global.css';
import { Providers } from './providers';

export const metadata = {
  title: 'Welcome to goaltime',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <body>
        <SpeedInsights />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
